### ISSUE TITLE
Combinations are not working for me

### ISSUE THREAD

**Issue by Hboni** [Hboni/francis#22]
I tried to apply multiplication, subtraction, comibination and division on one image and its threshold, and I always have this error :

    Traceback (most recent call last):
      File "C:\Users\Crayo\Documents\Python_projects\francis\francis\src\controller\connection.py", line 40, in <lambda>
        w.clicked.connect(lambda: eval(function)(widget))
      File "C:\Users\Crayo\Documents\Python_projects\francis\francis\src\controller\modules_fn.py", line 128, in substractImages
        im = core.substractImages(_IMAGES_STACK[ref_parent_name],
      File "C:\Users\Crayo\Documents\Python_projects\francis\francis\src\model\core.py", line 140, 
    in substractImages
        im_sub = im_sub.astype(getMinimumDtype(im_sub))
      File "C:\Users\Crayo\Documents\Python_projects\francis\francis\src\utils.py", line 20, in getMinimumDtype
        if np.array_equal(arr, arr.astype(dt), equal_nan=True):
      File "<__array_function__ internals>", line 4, in array_equal
    TypeError: _array_equal_dispatcher() got an unexpected keyword argument 'equal_nan'

And the application close...

**Comment by jeaunrg** [comment]
Sorry I forgot to warn you, you need to upgrade numpy to version 1.20.2, I think you have version 1.18.
I've already updated the requirements

**Comment by Hboni** [comment]
Oh yeah, I did not see your commit, it works great now! Thanks 🎉
